### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by mpreissner** [olympum/oarsman#2]
This project sounds like exactly what I'm looking for, so I hope you're planning on giving it some more attention.  For those of us not familiar with the GO language, or how to install and run programs written in GO, your documentation is a bit lacking.  Can you please detail system requirements, how to set up the environment so that all we have to do is type "oarsman xyz"?

FYI, I'm trying to set up on a raspberry pi.

**Comment by olympum** [comment]
Thanks, you are totally right, easy step by step installation instructions are required. Feel free to do a pull request with them.
